In [104]:
# importing pandas module  
import pandas as pd 
   
# reading csv file from url  
data =pd.read_excel (r'C:\Python37\Scripts\dealmoon-data.xlsx')

# Find free shipping and exclusions
data["Free Shipping"] = data["information"].str.contains(pat = 'Free shipping', regex = True) 
data["Exclusions Apply"] = data["information"].str.contains(pat = 'Exclusions Apply', regex = True) 

  
# new data frame with split value columns  by imformation looking for minimun
new = data["information"].str.split(r"Free shipping on | Exclusions", n = 2, expand = True) 
  
# making separate last name column from new data frame 
data["Conditions Free Shipping"]= new[1] 

# new data frame with split value columns 
new = data["Conditions Free Shipping"].str.split(r".", n = 2, expand = True) 
  
# making separate last name column from new data frame 
data["Conditions Free Shipping"]= new[0] 


# new data frame with split value columns 
new = data["Conditions Free Shipping"].str.split( n = 4, expand = True) 
  
# making separate last name column from new data frame 
data["Minimum Free Shipping"]= new[2] 
data.drop(columns =["Conditions Free Shipping"], inplace = True) 
new = data["Minimum Free Shipping"].str.split(r",|\(|expires|orders|\+|code|Fisher-Price|free|shipping|over|with|of|not|Deal|coupon|via|or|Mesh|get", n = 1, expand = True) 
  
# making separate last name column from new data frame 
data["Minimum Free Shipping"]= new[0] 

new=data["Minimum Free Shipping"].replace("2", "$2 items")
data["Minimum Free Shipping"]= new

new = data["Minimum Free Shipping"].str.split('，',n = 1, expand = True) 

# making separate last name column from new data frame 
data["Minimum Free Shipping"]= new[0] 

new = data["Minimum Free Shipping"].str.split("$",n = 1, expand = True) 
data["Minimum Free Shipping"]= new[1] 

data["Minimum Free Shipping"].fillna(value=pd.np.nan, inplace=True)
data["Minimum Free Shipping"].fillna("0", inplace = True)
data.loc[data['Free Shipping'] ==False, ['Minimum Free Shipping']] = 'N/A'

c:\python37\lib\site-packages\ipykernel_launcher.py:47: FutureWarning: The pandas.np module is deprecated and will be removed from pandas in a future version. Import numpy directly instead

In [105]:
# new data frame with split value columns 

new = data["information"].str.split(r"code", n = 1, expand = True) 

# making separate last name column from new data frame 
data["code"]= new[1] 
data.dropna(inplace = False) 
new = data["code"].str.split(r"\n \n \"", n = 1, expand = True) 
  
# making separate first name column from new data frame 
data["code1"]= new[0] 
new = data["code1"].str.split(r"\"\n \n" , n = 1, expand = True) 
  
# making separate first name column from new data frame 
data["code"]= new[1] 
data.drop(columns =["code1"], inplace = True)  
data

,day,retailer,information,Free Shipping,Exclusions Apply,Minimum Free Shipping,code
0,2020-04-24,adidas.com,Adidas offers the Ultraboost sneakers sale\n \...,True,False,49,APRIL
1,2020-04-24,adidas.com,Adidas offers the $40 for a $50 Gift Card on S...,False,False,N/A,None
2,2020-04-24,adidas.com,"Adidas offers the Yeezy 700 MNVN ""Phosphor"" fo...",True,False,0,None
3,2020-04-24,adidas.com,Adidas offers\n \n 30% off + free shipping\n ...,True,False,0,APRIL
4,2020-04-24,adidas.com,Adidas offers the slides and sandals sale\n \n...,True,False,0,APRIL
...,...,...,...,...,...,...,...
28068,2015-01-29,zara,Zara offers\n \n Up to 80% Off\n \n Winter Sa...,False,False,N/A,None
28069,2015-01-14,zara,Zara offers\n \n Up to 70% Off\n \n Winter Sa...,False,False,N/A,None
28070,2014-12-19,zara,Zara offers\n \n Up to 51% Off\n \n New Pre-S...,False,False,N/A,None
28071,2014-11-30,zara,Zara offers\n \n Up to 50% Off\n \n Select It...,False,False,N/A,None
28072,2014-11-28,zara,"Zara offers 30% OFF Entire Site ,discount pric...",False,False,N/A,None

In [106]:
data["retailer"]=data["retailer"].str.lower()
data["Clothing"] = data["retailer"].str.contains(pat = r'calvin-klein|adid|hm|lowes|express|gap|hollister|j crew|levis|nike|uniqlo|zara', regex = True) 
data["Superstore"] = data["retailer"].str.contains(pat = r"Target|walmart", regex = True) 
data["Wholesale"] = data["retailer"].str.contains(pat = r"costco|sams club", regex = True) 
data["Department Store"] = data["retailer"].str.contains(pat = r"bloomingdales|macys|neiman marcus|nordstrom", regex = True) 
data["Beauty"] = data["retailer"].str.contains(pat = r"sephora", regex = True) 
data["Electronic"] = data["retailer"].str.contains(pat = r"bestbuy", regex = True) 

data = pd.melt(data, id_vars=list(data.columns)[:7], value_vars=list(data.columns)[7:],
             var_name='Retailer Style', value_name='Dummy')
data=data[data.Dummy==True]

data.drop(columns=["Dummy"], inplace = True)
data

,day,retailer,information,Free Shipping,Exclusions Apply,Minimum Free Shipping,code,Retailer Style
0,2020-04-24,adidas.com,Adidas offers the Ultraboost sneakers sale\n \...,True,False,49,APRIL,Clothing
1,2020-04-24,adidas.com,Adidas offers the $40 for a $50 Gift Card on S...,False,False,N/A,None,Clothing
2,2020-04-24,adidas.com,"Adidas offers the Yeezy 700 MNVN ""Phosphor"" fo...",True,False,0,None,Clothing
3,2020-04-24,adidas.com,Adidas offers\n \n 30% off + free shipping\n ...,True,False,0,APRIL,Clothing
4,2020-04-24,adidas.com,Adidas offers the slides and sandals sale\n \n...,True,False,0,APRIL,Clothing
...,...,...,...,...,...,...,...,...
143454,2019-02-11,bestbuy,Best Buy offers the Red Dead Redemption: Game...,False,False,N/A,None,Electronic
143455,2019-02-11,bestbuy,Best Buy offers the $3.99/mo. for 24 months Mo...,False,False,N/A,None,Electronic
143456,2019-02-11,bestbuy,Best Buy offers the CyberPower GX1325U 1325VA...,True,False,0,None,Electronic
143457,2019-02-11,bestbuy,Best Buy offers the Dell Inspiron 7375 2-in-1...,True,False,0,None,Electronic
143458,2019-02-11,bestbuy,Best Buy offers the\n \n $29.99\n \n ($79.99)...,True,False,35,None,Electronic

In [107]:
data["information"]=data["information"].str.lower()
data["Bottoms"] = data["information"].str.contains(pat = r'jeans|pants|joggers|leggings|short|skirt|sweatpants', regex = True) 
data["Tops"] = data["information"].str.contains(pat = r'polos|shirts|t-shirts|sweaters|blouses|tanks|hoodies|sweatshirts|tees|bodysuits|tops', regex = True) 
data["Shoes"] = data["information"].str.contains(pat = r'sneakers|sandals|shoes|high heels|boots|heels|flats|slippers|loafer|flip flops', regex = True) 
data["Outerwear"] = data["information"].str.contains(pat = r'jackets|coat|outerwear', regex = True) 
data["Underwear"] = data["information"].str.contains(pat = r'bras|uderwear|panties|panty|socks|boxer', regex = True) 
data["Dresses"] = data["information"].str.contains(pat = r'dress', regex = True) 
data["Acessories"] = data["information"].str.contains(pat = r'bracelet|acessor|bags|hat|belt|watch|handbag|wallet|scar|sunglass|jewelry|neck|earing|ring', regex = True) 
data["Acessories"].value_counts()
data["TV"] = data["information"].str.contains(pat = r'tv', regex = True) 
data["Computers"] = data["information"].str.contains(pat = r'computer|laptop|monitor|deskto|ram|cpu|usb|tablet', regex = True) 
data["Headphones and Speakers"] = data["information"].str.contains(pat = r'headphones|earbuds|earpods|speaker', regex = True) 
data["Makeup"] = data["information"].str.contains(pat = r'sephora|makeup|palette', regex = True) 
data["Eyes Makeup"] = data["information"].str.contains(pat = r'eye|eye|mascara|Masca', regex = True) 
data["Skin Makeup"] = data["information"].str.contains(pat = r'blushs|bronzer|foundation|Foundation|Blus|Bronz|Primer|primer', regex = True) 
data["Lips"] = data["information"].str.contains(pat = r'Lips|lip|Balm|balm', regex = True) 
data["Skin Care"] = data["information"].str.contains(pat = r'moisturizer|Moisturizer|Skin Care|skin care|toner|Skin', regex = True) 
data["Sitewide"] = data["information"].str.contains(pat = r'sitewide|entire site|entire store|purchase', regex = True) 
data

,day,retailer,information,Free Shipping,Exclusions Apply,Minimum Free Shipping,code,Retailer Style,Bottoms,Tops,...,Acessories,TV,Computers,Headphones and Speakers,Makeup,Eyes Makeup,Skin Makeup,Lips,Skin Care,Sitewide
0,2020-04-24,adidas.com,adidas offers the ultraboost sneakers sale\n \...,True,False,49,APRIL,Clothing,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2020-04-24,adidas.com,adidas offers the $40 for a $50 gift card on s...,False,False,N/A,None,Clothing,False,False,...,False,False,False,False,False,False,False,False,False,False
2,2020-04-24,adidas.com,"adidas offers the yeezy 700 mnvn ""phosphor"" fo...",True,False,0,None,Clothing,False,False,...,False,False,False,False,False,False,False,False,False,False
3,2020-04-24,adidas.com,adidas offers\n \n 30% off + free shipping\n ...,True,False,0,APRIL,Clothing,False,True,...,False,False,False,False,False,False,False,False,False,False
4,2020-04-24,adidas.com,adidas offers the slides and sandals sale\n \n...,True,False,0,APRIL,Clothing,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
143454,2019-02-11,bestbuy,best buy offers the red dead redemption: game...,False,False,N/A,None,Electronic,False,False,...,False,False,False,False,False,False,False,False,False,False
143455,2019-02-11,bestbuy,best buy offers the $3.99/mo. for 24 months mo...,False,False,N/A,None,Electronic,False,False,...,False,False,False,False,False,False,False,False,False,False
143456,2019-02-11,bestbuy,best buy offers the cyberpower gx1325u 1325va...,True,False,0,None,Electronic,False,False,...,False,False,False,False,False,False,False,False,False,False
143457,2019-02-11,bestbuy,best buy offers the dell inspiron 7375 2-in-1...,True,False,0,None,Electronic,False,False,...,False,False,True,False,False,False,False,False,False,False
143458,2019-02-11,bestbuy,best buy offers the\n \n $29.99\n \n ($79.99)...,True,False,35,None,Electronic,False,False,...,False,False,False,False,False,False,False,False,False,False

In [108]:
data = pd.melt(data, id_vars=list(data.columns)[:8], value_vars=list(data.columns)[8:24],
             var_name='Product', value_name='Dummy')
data=data[data.Dummy==True]
data.drop(columns=["Dummy"], inplace = True)
data

,day,retailer,information,Free Shipping,Exclusions Apply,Minimum Free Shipping,code,Retailer Style,Product
134,2019-11-16,adidas.com,adidas offers an\n \n extra 30% off\n \n wome...,True,False,0,GIVEADI,Clothing,Bottoms
138,2019-11-14,adidas.com,adidas offers\n \n 25% off\n \n women's worko...,True,False,0,GIFT25,Clothing,Bottoms
147,2019-11-12,adidas.com,dealmoon 11.11 exclusive!\r\nadidas offers an\...,False,False,N/A,ADIMOON,Clothing,Bottoms
218,2019-07-24,adidas.com,adidas offers an\n \n extra 20% off\n \n on l...,True,False,0,EXTRA20,Clothing,Bottoms
226,2019-07-06,adidas.com,adidas offers an\n \n up to 50% off + extra 3...,True,False,0,SAVE30,Clothing,Bottoms
...,...,...,...,...,...,...,...,...,...
415529,2019-12-06,bestbuy,best buy offers the purchase to get $25 free b...,False,False,N/A,None,Electronic,Sitewide
415924,2019-10-18,bestbuy,best buy offers\n \n save $100 + get $150 bes...,False,False,N/A,None,Electronic,Sitewide
416617,2019-06-13,bestbuy,best buy offers\n \n free $50 e-gift card\n \...,True,False,0,None,Electronic,Sitewide
416678,2019-06-02,bestbuy,best buy offers purchase $50 or more in select...,False,False,N/A,None,Electronic,Sitewide
417012,2019-04-08,bestbuy,best buy offers my best buy® members\n \n get...,False,False,N/A,None,Electronic,Sitewide

In [109]:
data["Week"]=data['day'].dt.week
data["year"]=data['day'].dt.year
data["promotion"]=True
data

,day,retailer,information,Free Shipping,Exclusions Apply,Minimum Free Shipping,code,Retailer Style,Product,Week,year,promotion
134,2019-11-16,adidas.com,adidas offers an\n \n extra 30% off\n \n wome...,True,False,0,GIVEADI,Clothing,Bottoms,46,2019,True
138,2019-11-14,adidas.com,adidas offers\n \n 25% off\n \n women's worko...,True,False,0,GIFT25,Clothing,Bottoms,46,2019,True
147,2019-11-12,adidas.com,dealmoon 11.11 exclusive!\r\nadidas offers an\...,False,False,N/A,ADIMOON,Clothing,Bottoms,46,2019,True
218,2019-07-24,adidas.com,adidas offers an\n \n extra 20% off\n \n on l...,True,False,0,EXTRA20,Clothing,Bottoms,30,2019,True
226,2019-07-06,adidas.com,adidas offers an\n \n up to 50% off + extra 3...,True,False,0,SAVE30,Clothing,Bottoms,27,2019,True
...,...,...,...,...,...,...,...,...,...,...,...,...
415529,2019-12-06,bestbuy,best buy offers the purchase to get $25 free b...,False,False,N/A,None,Electronic,Sitewide,49,2019,True
415924,2019-10-18,bestbuy,best buy offers\n \n save $100 + get $150 bes...,False,False,N/A,None,Electronic,Sitewide,42,2019,True
416617,2019-06-13,bestbuy,best buy offers\n \n free $50 e-gift card\n \...,True,False,0,None,Electronic,Sitewide,24,2019,True
416678,2019-06-02,bestbuy,best buy offers purchase $50 or more in select...,False,False,N/A,None,Electronic,Sitewide,22,2019,True
417012,2019-04-08,bestbuy,best buy offers my best buy® members\n \n get...,False,False,N/A,None,Electronic,Sitewide,15,2019,True

In [111]:
output=[]          
for x in data["retailer"] :
     if x not in output:
        output.append(x)

P=[]
for x in data["Product"] :
     if x not in P:
        P.append(x)

for x in output:
    data1=data[data.retailer==x]
    start=data1['day'].min()
    end=data1['day'].max()
    df = pd.DataFrame({"Date": pd.date_range(start, end)})
    df["Week"] = df.Date.dt.weekofyear.astype(int)
    df["year"] = df.Date.dt.year.astype(int)
    df["Control"]=df["Week"]+df["year"]*100
    J=[]
    for z in data1["Retailer Style"]:
            J=z
    for y in P:
        data2=data1[data.Product==y]
        result = pd.merge(left=df, right=data2, how='left', left_on=['year','Week'], right_on=['year','Week'])
        result.drop_duplicates('Control',keep='first',inplace=True)
        result.drop(columns =["Control","Date"], inplace = True)
        result["Product"]=y
        result["retailer"]=x
        result["Retailer Style"]=J
        result.to_excel( x+y+'.xlsx' )
result

c:\python37\lib\site-packages\ipykernel_launcher.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

,Week,year,day,retailer,information,Free Shipping,Exclusions Apply,Minimum Free Shipping,code,Retailer Style,Product,promotion
0,4,2017,2017-01-28,sephora,sephora.com offers the hello kitty x tangle t...,False,False,N/A,None,Beauty,Sitewide,True
45,5,2017,2017-02-04,sephora,sephora.com offers kopari skincare products fr...,False,False,N/A,None,Beauty,Sitewide,True
73,6,2017,2017-02-10,sephora,sephora.com offers givenchy my makeup accessor...,False,False,N/A,None,Beauty,Sitewide,True
115,7,2017,2017-02-16,sephora,sephora.com offers\n \n free one deluxe sampl...,False,False,N/A,TWOLIPS,Beauty,Sitewide,True
136,8,2017,2017-02-23,sephora,sephora.com offers\n \n free one deluxe sampl...,False,False,N/A,POSHPICKS,Beauty,Sitewide,True
...,...,...,...,...,...,...,...,...,...,...,...,...
3456,13,2020,NaT,sephora,NaN,NaN,NaN,NaN,NaN,Beauty,Sitewide,NaN
3463,14,2020,NaT,sephora,NaN,NaN,NaN,NaN,NaN,Beauty,Sitewide,NaN
3470,15,2020,NaT,sephora,NaN,NaN,NaN,NaN,NaN,Beauty,Sitewide,NaN
3477,16,2020,2020-04-19,sephora,sephora.com offers\n \n free shipping sitewid...,False,False,N/A,None,Beauty,Sitewide,True
3547,17,2020,2020-04-24,sephora,sephora.com offers\n \n up to 20% off\n \n wi...,False,False,N/A,SPRINGSAVE,Beauty,Sitewide,True

In [115]:
for x in output:
    dh =pd.read_excel(x+P[0]+'.xlsx')
    for y in P[2:16]:
        data =pd.read_excel(x+y+'.xlsx')
        dh=dh.append(data, ignore_index=True)
    dh["code"].fillna(" ", inplace = True) 
    dh["Free Shipping"].fillna(0, inplace = True) 
    dh["Minimum Free Shipping"].fillna(0, inplace = True) 
    dh["promotion"].fillna(0, inplace = True) 
    dh.drop(columns =["Unnamed: 0"], inplace = True)
    dh.to_excel( x+'_Data.xlsx' )

In [117]:
import numpy as np
data =pd.read_excel(output[0]+'_Data.xlsx')
data.sort_values(['year', 'Week'], ascending=[False, False])
Training , Testing = np.split(data, [int(.75*len(data))])
for x in output[1:len(output)]:
    data=pd.read_excel(x+'_Data.xlsx') 
    data.sort_values(['year', 'Week'], ascending=[False, False])
    Training2 , Testing2 = np.split(data, [int(.75*len(data))])
    Testing=Testing.append(Testing2, ignore_index=True)
    Training=Training.append(Training2, ignore_index=True)

In [123]:
Training.drop(columns =["information","day","Unnamed: 0"], inplace = True) 
Testing.drop(columns =["information","day","Unnamed: 0"], inplace = True) 
Training.to_excel('Training_complete.xlsx' )
Testing.to_excel('Testing_complete.xlsx' )
Training.drop(columns =["Exclusions Apply","Free Shipping","code","Retailer Style","Minimum Free Shipping"], inplace = True) 
Testing.drop(columns =["Exclusions Apply","Free Shipping","code","Retailer Style","Minimum Free Shipping"], inplace = True)

       Unnamed: 0  Week  year    retailer      Product  promotion
0               0    19  2015  adidas.com      Bottoms          0
1               1    20  2015  adidas.com      Bottoms          0
2               2    21  2015  adidas.com      Bottoms          0
3               3    22  2015  adidas.com      Bottoms          0
4               4    23  2015  adidas.com      Bottoms          0
...           ...   ...   ...         ...          ...        ...
71582        1907    41  2017     sephora  Skin Makeup          0
71583        1908    42  2017     sephora  Skin Makeup          1
71584        1909    43  2017     sephora  Skin Makeup          1
71585        1910    44  2017     sephora  Skin Makeup          1
71586        1911    45  2017     sephora  Skin Makeup          1

[71587 rows x 6 columns]

In [125]:
Training = pd.get_dummies(Training)
Testing = pd.get_dummies(Testing)
Training.to_excel('Training.xlsx' )
Testing.to_excel('Testing.xlsx' )